source 'https://rubygems.org'

gem 'roda'
gem 'tilt'
gem 'sinatra-flash'
gem 'rack_csrf'
gem 'unicorn'
gem 'pg'
gem 'sequel'
gem 'sequel_pg'
gem 'subset_sum'
gem 'bcrypt-ruby'
gem 'autoforme', '>= 1.0.0'
