source 'https://rubygems.org'

gem 'roda', '>= 1.1'
gem 'tilt'
gem 'sass'
gem 'erubis'
gem 'rack-protection'
gem 'rack_csrf'
gem 'unicorn'
gem 'pg'
gem 'sequel'
gem 'sequel_pg'
gem 'subset_sum'
gem 'bcrypt-ruby'
gem 'autoforme', '>= 1.0.1'
